### ISSUE TITLE
unicode undefined

### ISSUE THREAD

**Issue by ncmadhan1989** [BrianHung/EmojiPicker#1]
![error](https://user-images.githubusercontent.com/44596222/90642096-98149180-e24f-11ea-8de9-8e2ea5382516.png)
i am facing this issue,can you help on this??

**Comment by BrianHung** [comment]
Are you loading the emoji data correctly? From the readme,
```js
import { EmojiPicker } from 'react-twemoji-picker';
import EmojiData from "react-twemoji-picker/data/twemoji.json";

const emojiData = Object.freeze(EmojiData)
const handleEmojiSelect = (emoji: EmojiObject) => console.log(emoji)

<EmojiPicker emojiData={emojiData} handleEmojiSelect={handleEmojiSelect}/>
```

Post how you're using the EmojiPicker if you can.

**Comment by ncmadhan1989** [comment]
> Are you loading the emoji data correctly? From the readme,
> 
> ```js
> import { EmojiPicker } from 'react-twemoji-picker';
> import EmojiData from "react-twemoji-picker/data/twemoji.json";
> 
> const emojiData = Object.freeze(EmojiData)
> const handleEmojiSelect = (emoji: EmojiObject) => console.log(emoji)
> 
> <EmojiPicker emojiData={emojiData} handleEmojiSelect={handleEmojiSelect}/>
> ```
> 
> Post how you're using the EmojiPicker if you can.

import './mystyle.css';
import  type { EmojiObject } from '../../../../node_modules/react-twemoji-picker/src/index';
import { EmojiPicker, EmojiPickerRef  } from  '../../../../node_modules/react-twemoji-picker/src/index';
import * as  EmojiData from "../../../../node_modules/react-twemoji-picker/data/twemoji.json";
//D:\spfx1.10\node_modules\react-twemoji-picker\data\twemoji.json
const emojiData = Object.freeze(EmojiData);
const handleEmojiSelect = (emoji: EmojiObject) => console.log(emoji);

const ref = React.createRef<EmojiPickerRef>();
const handleSearch = (query: string) => ref.current.search(query);

in render 

```
<div style={{'display': 'flex', 'flexDirection': 'column', 'height': '100vh', 'justifyContent': 'center', 'alignItems': 'center'}}>
    <h1>Emoji Picker</h1>
    <p>a virtualized <a href="https://twemoji.twitter.com/">twemoji</a> picker written in react and typescript</p>
    <EmojiPicker {...EmojiPickerProps}/>
    <input onChange={event => handleSearch(event.target.value)} placeholder="search"></input>
    <a href="https://github.com/BrianHung/EmojiPicker">source code</a>
  </div>
```

**Comment by BrianHung** [comment]
Can you try this instead?
```js
import EmojiData from "react-twemoji-picker/data/twemoji.json";
```
Also `console.log(EmojiData)` to see that the data is correctly imported.

**Comment by ncmadhan1989** [comment]
> Can you try this instead?
> 
> ```js
> import EmojiData from "react-twemoji-picker/data/twemoji.json";
> ```
> 
> Also `console.log(EmojiData)` to see that the data is correctly imported.

console is working fine,i am getting this error now
![ree2](https://user-images.githubusercontent.com/44596222/90731565-77981600-e2e7-11ea-9f6a-275201501194.png)

**Comment by BrianHung** [comment]
Try passing in `emojiData={EmojiData.default}`. `emojiData` should be an object with category as its keys, and array of emoji objects as its values.

**Comment by ncmadhan1989** [comment]
> Try passing in `emojiData={EmojiData.default}`. `emojiData` should be an object with category as its keys, and array of emoji objects as its values.

thanks a lot for the  quick help its working now 
and **EmojiData.default** this not working i used **emojiData['default']**
another think i have added **"resolveJsonModule": true,**  in  tsconfig.json 
please update this  things in your plugin,this may helps some newones
