### ISSUE TITLE
img format support.

### ISSUE THREAD

**Issue by neetigyachahar** [BrianHung/EmojiPicker#4]
I have tried a lot of Twemoji pickers in React but this one seems to be the best. But when I tried to integrate it with my website which is already pretty heavy, upon scrolling the emoji picker, the whole UI got hung.

Since my React project is in javascript, I removed all Typescript syntax while using the `EmojiPicker` component. I have even tried to replicate your demo website code in js but no luck.

Finally, I think although this project uses `react-window`, svg is still heavy for the browser.

Could there be a simple way where `svg` sprite's part can be provided to `src` in `img` tag and we can use this format with a prop on `EmojiPicker` so that browser doesn't need to parse `svg`?

Or is it not ok to use JavaScript instead of TypeScript while using the `EmojiPicker` component? Please guide me.

**Comment by BrianHung** [comment]
> But when I tried to integrate it with my website which is already pretty heavy, upon scrolling the emoji picker, the whole UI got hung.

Try re-cloning this repo again. There was a [bug with Chromium](https://bugs.chromium.org/p/chromium/issues/detail?id=1116738) when it came to cache-ing svg use elements in developement, so I've switched to img elements instead.

> Since my React project is in javascript, I removed all Typescript syntax while using the EmojiPicker component. I have even tried to replicate your demo website code in js but no luck.

Typescript is only used when developing, and transcompiles down to Javascript when used in production. Make sure you're using the `dist` folder which has `js` files, not the `src` files which has `ts` files.

> Could there be a simple way where svg sprite's part can be provided to src in img tag and we can use this format with a prop on EmojiPicker so that browser doesn't need to parse svg?

Yep, that change was made in this [recent commit](https://github.com/BrianHung/EmojiPicker/commit/e49618a756948e4af916d10bb94634734ed64da4). Check the demo: https://brianhung.info/EmojiPicker/ you should see img src being used.

**Comment by neetigyachahar** [comment]
Thanks for your guidance. As I re-cloned the repo the scrolling issue is completely gone and `img` elements appeared.

>  Typescript is only used when developing, and transcompiles down to Javascript when used in production. Make sure you're using the dist folder which has js files, not the src files which has ts files.

I simply used `npm install --save github:brianhung/emojipicker` to clone this repo which added the `dist` folder to my repo as expected. TypeScript code I mentioned was from the `./website/index.tsx`. 

Although right now there is no issue in scrolling the picker, but the emojis are not appearing. I tried multiple times.
Here is a simple demonstration of the issue on repl.it: [TwemojiPicker in React](https://repl.it/@neetigyachahar/twemojipicker)

![image](https://user-images.githubusercontent.com/42602123/108989933-2d3f8980-76bc-11eb-9d59-db6af9162252.png)

Please review the issue and suggest some way out. Thank you.

**Comment by BrianHung** [comment]
> TypeScript code I mentioned was from the ./website/index.tsx.

The code within `./website` is only for the demo https://brianhung.github.io/EmojiPicker, and is not needed if you're using the `dist` library. If you're using the website source code as an example, yeah then it's fine to remove the types and have it in regular javascript.

> Although right now there is no issue in scrolling the picker, but the emojis are not appearing. I tried multiple times.

Ah, you found a bug: I forgot to copy the new svg over from `src` to `dist` and `data`. That has been fixed [here](https://github.com/BrianHung/EmojiPicker/commit/00f8007e482c1b3558f4ca5006a77c249d72dc67). Try re-cloning the repo now (also make sure to uninstall then reinstall so it's not cached by npm or yarn). :)

**Comment by neetigyachahar** [comment]
I am so happy & excited that I was able to help and the TwemojiPicker is working like a charm now, which brings my months of struggle to end. Thanks for creating this amazing project.
