### ISSUE TITLE
unifiedToNative failing to convert

### ISSUE THREAD

**Issue by Bartaf83** [BrianHung/EmojiPicker#5]
Hey,
As shows [this screenshot](https://i.imgur.com/FlWWIcR.gif), most emojis work fine , but this one 
`{"unicode":"1f972","name":"smiling-face-with-tear","keywords":["smiling face with tear","grateful","proud","relieved","smiling","tear","touched"]} `
fails to be converted by unifiedToNative and i'm getting a 🥲 character.
I dunno if that's the only one.

**Comment by BrianHung** [comment]
The `unifiedToNative` function is correct. The issue I'm guessing is that your OS (Windows?) doesn't have "smiling-face-with-tear" as a native emoji.

Check if you also get a 🥲 character here: https://emojipedia.org/smiling-face-with-tear/ or https://unicode.org/emoji/charts/full-emoji-list.html#1f972.

It's a relatively new emoji (added in Emoji 13.0 2020) so it'd make sense not all OS support it yet.
